apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-07-17T00:52:17Z"
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.10.1
    chart: kube-prometheus-stack-45.10.1
    heritage: Helm
    project: gd9
    release: kube-prometheus-stack
  name: kube-prometheus-stack-operator
  resourceVersion: "22021"
  uid: 8f79ce4a-4a4b-4ae8-ab47-48cd01509109
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-prometheus-stack-operator
subjects:
- kind: ServiceAccount
  name: kube-prometheus-stack-operator
  namespace: monitoring