commonLabels:
  project: gd9

namespaceOverride: "monitoring"
defaultRules:
  create: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheus:
  enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::240195868935:role/prometheus"
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: main
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: prometheus
    podMonitorSelector:
      matchLabels:
        prometheus: main
    podMonitorNamespaceSelector:
      matchLabels:
        monitoring: prometheus

    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
        selector: {}



grafana:
  enabled: false