commonLabels:
  project: gd9

namespaceOverride: "monitoring"
defaultRules:
  create: false

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false